version: '3'
services:
  html_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: employees-api-product
    container_name: employees-api-product-container
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./static:/usr/share/nginx/static
      - ./templates:/usr/share/nginx/html
      - .env:/app/.env
